# Site
repository: sproogen/resume-theme
favicon: images/favicon.ico

# Content configuration version
version: 2

# Personal info
name: Donald Sayers
title: IT Manager - Maker
email: me@donaldsayers.com
website: www.donaldsayers.com

# Dark Mode (true/false/never)
darkmode: true

# Social links
#twitter_username: DonaldSayers
#github_username:  sproogen
# stackoverflow_username: "00000001"
# dribbble_username: jekyll
# facebook_username: jekyll
# flickr_username: jekyll
#instagram_username: DonaldSayers
#linkedin_username: jameswgrant
# xing_username: jekyll
# pinterest_username: jekyll
#youtube_username: globalmtb
# googleplus_username: +jekyll
# orcid_username: 0000-0000-0000-0000

# Additional icon links
#additional_links:
##  url: https://www.itsgoingto.be
# - title: another link
#   icon: font awesome brand icon name (eg. fab fa-twitter) (https://fontawesome.com/icons?d=gallery&m=free)
#   url: Link url (eg. https://google.com)

# Google Analytics and Tag Manager
# Using more than one of these may cause issues with reporting
# gtm: "GTM-0000000"
# gtag: "UA-00000000-0"
# google_analytics: "UA-00000000-0"

# About Section
about_title:
about_profile_image: images/Donald Sayers.jpg
about_content: | # this will include new lines to allow paragraphs
  Hi, my name's Donald I'm an IT manager for a company of 150+ people. As well as working in IT, I like to make things and tinker with electronics. I ran an independent computer repair company for about 15 years.

  I am most skilled in: <mark>Computer Stuff</mark>, <mark>3D Printing</mark>, and <mark>Petting Cats</mark>.

content:

  - title: Experience # Title for the section
    layout: list # Type of content section (list/text)
    content:
      - layout: left
        border: weak
        title: Chattanooga Fire Protection
        sub_title: IT Manager
        caption: 2021 - Present
        quote: >
          Implementing tech for a company that was using paper for just about everything.
        description: | # this will include new lines to allow paragraphs
            I manage all the IT needs for the company. Deploying phones and laptops and managing our networks and servers. A large part of the job has been streamlining existing processes. I've digitized timesheets, workorders, billing, and many other things that were all being done on paper.

            It's been a huge challenge to get everyone onboard. I spend time building trust with fellow employees so that when we make a change they are less likely to push back. Undertaking the task has been fun and rewarding.
            <br/><br/>

            At Chattanooga Fire I use;

            <mark>Sage 300</mark> made tools to import data to and from other systems.

            <mark>Crystal Reports</mark> I created reports for job costs, payroll, taxes, and to make looking trough massive amounts of data more accessable.

            <mark>Excel/Google Pages</mark> Used mostly for pivot tables and for making tools for importing and translating data from one database to another.

            <mark>Windows Server</mark> is used to host our financial software. Making The server secure while allowing remote access through a VPN has helped allow people in the compan better access to the data.
            <br/><br/>


# Footer
footer_show_references: true
# references_title: References on request (Override references text)

# Build settings
remote_theme: sproogen/resume-theme

sass:
  sass_dir: _sass
  style: compressed

plugins:
 - jekyll-seo-tag
