# Site
repository: sproogen/resume-theme
favicon: images/favicon.ico

# Content configuration version
version: 2

# Personal info
name: Donald Sayers
title: IT Manager - Maker
email: me@donaldsayers.com
website: www.donaldsayers.com

# Dark Mode (true/false/never)
darkmode: true

# Social links
twitter_username: DonaldSayers
#github_username:  sproogen
# stackoverflow_username: "00000001"
# dribbble_username: jekyll
# facebook_username: jekyll
# flickr_username: jekyll
instagram_username: DonaldSayers
#linkedin_username: jameswgrant
# xing_username: jekyll
# pinterest_username: jekyll
#youtube_username: globalmtb
# googleplus_username: +jekyll
# orcid_username: 0000-0000-0000-0000

# Additional icon links
#additional_links:
##  url: https://www.itsgoingto.be
# - title: another link
#   icon: font awesome brand icon name (eg. fab fa-twitter) (https://fontawesome.com/icons?d=gallery&m=free)
#   url: Link url (eg. https://google.com)

# Google Analytics and Tag Manager
# Using more than one of these may cause issues with reporting
# gtm: "GTM-0000000"
# gtag: "UA-00000000-0"
# google_analytics: "UA-00000000-0"

# About Section
about_title:
about_profile_image: images/Donald Sayers.jpg
about_content: | # this will include new lines to allow paragraphs
  Hi, my name's Donald I'm an IT manager for a company of 150+ people. As well as working in IT, I like to make things and tinker with electronics. I ran an independent computer repair company for about 15 years.

  I am most skilled in: <mark>Computer Stuff</mark>, <mark>3D Printing</mark>, and <mark>Ordering Pizza</mark>.

content:

  - title: Experience # Title for the section
    layout: list # Type of content section (list/text)
    content:
      - layout: left
        title: Chattanooga Fire Protection
        sub_title: IT Manager
        caption: 2021 - Present
        quote: >
          Implementing tech for a company that was using paper for just about everything.
        description: | # this will include new lines to allow paragraphs
            I manage all the IT needs for the company. Deploying phones and laptops and managing our networks and servers. A large part of the job has been streamlining existing processes. I've digitized timesheets, workorders, billing, and many other things that were all being done on paper.

            It's been a huge challenge to get everyone onboard, but undertaking the task has been fun and rewarding.

      - layout: left
        title: iFixie Computer Repair
        link: ifixie.com
        sub_title: Owner
        caption: 2009 - 2021
        quote: >
          I loved being greeted every day with a new challange.
        description: | # this will include new lines to allow paragraphs
            I ran a computer repair shop in the downtown area. I repaired Macs and PCs as well as doing onsite work for homes and businesses. Onsite I set up networks, servers and home theater systems. Running this business was a very rewarding endeavor, I was able to learn new things and enjoyed the problem-solving challenges I was greeted with every day.

      - layout: left
        title: Medium
        sub_title: Creative Director
        caption: 2010 - 2011
        description: | # this will include new lines to allow paragraphs
            Medium was a bootcamp for learning development and design. I learned here that I work best with a challenge. I worked with clients, developers and designers to make sure that our clients’ needs were met and exceeded. Working in such a creative environment kept work fresh every day.

      - layout: left
        title: Staples
        sub_title: Easy Tech
        caption: 2007 - 2009
        description: | # this will include new lines to allow paragraphs
            Staples is where I was able to grow my love for technology. I was responsible for fixing computers and training new employees. I was given the freedom to develop new and more efficient ways to repair and track repairs customers computers.

  - title: Projects # Title for the section
    layout: list # Type of content section (list/text)
    content:
      - layout: top-middle
        title: Voyager Wallets
        link: voyagerwallet.com
        additional_links:
        description: | # this will include new lines to allow paragraphs
          After being unhappy with the wallets available on the market, I created a premium aluminum wallet. I spent years perfecting the design in wood and plastic, and now have them CNC machined out of a block of aluminum.

      - layout: top-middle
        title: 3D Printing Designs
        link: www.printables.com/@DonaldSayers
        additional_links:
        description: | # this will include new lines to allow paragraphs
          I love sharing some of the things I have created that could be useful to others. Printables has allowed me to share the designs far and wide. One of my most popular files has over 11k downloads, and people have posted over 300 makes from all over the world.

      - layout: top-middle
        title: Custom NES Grips
        link: nes4.fun
        additional_links:
        description: | # this will include new lines to allow paragraphs
          Available shells for the NES were lacking in comfort. I fixed that. Modeled off of a popular modern console controller, you are free to play your old games with the comfort of modern controllers.

      - layout: top-middle
        title: serviceindustry.tips
        link: serviceindustry.tips
        additional_links:
        description: | # this will include new lines to allow paragraphs
          Thanks to the hard work from some great friends, we were able to help over 74,000 service industry workers receive 124,000 generous tips during the pandemic. I started this project from a google spreadsheet and then managed an amazing team of developers and volunteers to help people that were suddenly out of jobs.

  - title: Education # Title for the section
    layout: list # Type of content section (list/text)
    content:
      - layout: left
        title: Middle Tennessee State University
        caption: 2006 - 2007
        sub_title: Incomplete
        description: | # this will include new lines to allow paragraphs
          At MTSU I was in the music program, and was studying computer science.

      - layout: left
        title: Chattanooga State Community College
        caption: 2009 - 2010
        sub_title: Incomplete
        description: | # this will include new lines to allow paragraphs
          Studied computer science and took some cources in drafting and 3D CAD.




  - title: A Little More About Me
    layout: text
    content: | # this will include new lines to allow paragraphs
      Alongside my interest in computer Science some of my other interests and hobbies are:
      - 3D Printing
      - Laser Cutting
      - Electronic Circuit Design
      - Prop Making
      - Product Design
      - Manufacturing


# Footer
footer_show_references: true
# references_title: References on request (Override references text)

# Build settings
remote_theme: sproogen/resume-theme

sass:
  sass_dir: _sass
  style: compressed

plugins:
 - jekyll-seo-tag
